language: node_js
node_js:
  - "8"
dist: trusty
sudo: required
cache:
  directories:
    - node_modules
branches:
  only:
  - master
before_script:
  - npm install -g @angular/cli
addons:
  chrome: stable
script:
- ng lint
- ng build --prod
jobs:
  include:
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t my-ionic-web-app .
      - docker images
      - docker tag my-ionic-web-app:latest phamtai/my-first-repo:ionic-web-app
      - docker push $DOCKER_USERNAME/my-first-repo